### ISSUE TITLE
php Warning message in bitly.php 

### ISSUE THREAD

**Issue by johnmontfx** [warfare-plugins/social-warfare#285]
Just installed Version 2.1.1 and am getting the following warnings in php.log on my dev server (and production):

[31-Oct-2016 15:05:17 UTC] PHP Warning:  Illegal string offset 'url' in /wp-content/plugins/social-warfare/functions/bitly.php on line 299

Attempted to adjust and re-save bitly settings in case something happened upon upgrade, but didn't fix the problem.

**Comment by Nicholas-Cardot** [comment]
Thanks for reporting that. I'll look into this first thing tomorrow morning and get it fixed right up.

**Comment by Nicholas-Cardot** [comment]
For the life of me, I just can't figure out why that's giving off that error.

**Comment by joshin42** [comment]
It's more than just a warning. My clients (3 of them, each with their own subscription) are having problems editing or creating posts.

When they submit, they see see this lovely result.

![error message](https://cloud.githubusercontent.com/assets/1756222/19936613/4462a7a2-a0db-11e6-82ce-aa1d8c0c679e.png)

The environment is nothing too special: PHP 7.0.11 + Apache 2.4 with the Event MPM

**Comment by nutsandbolts** [comment]
That is a separate bug - we just pushed an update that will resolve it.

**Comment by Nicholas-Cardot** [comment]
@joshin42 Just update to 2.1.2 and that should go away immediately. Sorry about that!

**Comment by joshin42** [comment]
Cool, thanks.

**Comment by joshin42** [comment]
Updated to 2.1.2 and the major bug seems better for them. Thank you!

I am still seeing the much more minor:
[Wed Nov 02 09:27:38.342338 2016] [proxy_fcgi:error] [pid 20774:tid 139866913535744] [client 142.239.254.10:63670] AH01071: Got error 'PHP message: PHP Warning:  Illegal string offset 'url' in /home/www/whphx4/EXAMPLE.com/htdocs/wp-content/plugins/social-warfare/functions/bitly.php on line 297\n', referer: http://www.EXAMPLE.com/thank-you-apple-number-match

Let me know if I can provide more info, or help test. We have about 10 folk using SW.

**Comment by adelf** [comment]
Same warning as @joshin42's at 2.1.2 version. It pollutes our logs :) Fix please.

**Comment by Nicholas-Cardot** [comment]
Okay, I think I have this fixed. If you uninstall and reinstall from the WordPress repo, this should go away.

1. Deactivate and Delete the current install of Social Warfare
2. Go to Plugins > Add new and search for Social Warfare in the repository
3. Install and Activate it 

Did that get it?

**Comment by joshin42** [comment]
Thanks @Nicholas-Cardot! 

I've installed it on 2 sites. So far, your fix seems to be working. I appreciate your effort!

**Comment by Nicholas-Cardot** [comment]
Awesome! Great to hear!
